steps:
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: ['-c', 'mvn install']

# Build Container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/zapatopia-web:$BUILD_ID', '.']

# Push to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/zapatopia-web:$BUILD_ID"]

# Prepare Kubernetes Manifest
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-e'
  - '-c'
  - |
    # Substitute variables in Kubernetes manifest
    mkdir -p target
    cat zapatopia-web-deployment.yaml | \
      sed s/BUILD_ID/$BUILD_ID/g | \
      sed s/PROJECT_ID/$PROJECT_ID/g \
      > target/zapatopia-web-deployment.yaml

# Perform Kubernetes Deployment
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-e'
  - '-c'
  - |
    gcloud container clusters get-credentials --project="$PROJECT_ID" --zone="us-east1-c" "microservices"

    kubectl apply -f target/zapatopia-web-deployment.yaml
images:
- 'gcr.io/$PROJECT_ID/zapatopia-web'