apiVersion: v1
kind: ConfigMap
metadata:
  name: zapatopia-web-config
  namespace: default
data:
  mysql_host: 127.0.0.1
  redis_host: 127.0.0.1
  redis_password: admin123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zapatopia-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zapatopia-web
  template:
    metadata:
      name: zapatopia-web
      labels:
        app: zapatopia-web
    spec:
      containers:
        - name: zapatopia-web
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: zapatopia-web-config
                  key: mysql_host

            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: zapatopia-config
                  key: mysql_db

            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: zapatopia-config
                  key: mysql_user

            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: zapatopia-config
                  key: mysql_password

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: zapatopia-web-config
                  key: redis_host

            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: zapatopia-web-config
                  key: redis_password
          image: gcr.io/PROJECT_ID/zapatopia-web:BUILD_ID